#ifndef MATRIZ_H
#define MATRIZ_H

void CM();//CRIA MATRIZ
void DM();//DESTRUIR MATRIZ
void IM();//IMPRIMIR MATRIZ
void AE();//ATRIBUI ELEMENTO A MATRIZ
void AL();//ATRIBUI LINHA A MATRIZ
void AC();//ATRIBUI COLUNA A MATRIZ
void TM();//TRANSPOR UMA MATRIZ
void SM();//SOMAR DUAS MATRIZES
void DV();//DIVIDIR UMA MATRIZ POR OUTRA --> ELEMENTO POR ELEMENTO
void MM();//MULTIPLICAR UMA MATRIZ POR OUTRA
void ME();//MULTIPLICAR UMA MATRIZ POR OUTRA --> ELEMENTO POR ELEMENTO
void FE();//FINALIZA A EXECUÇÃO DO PROGRAMA

#endif
